blueprint:
  name: Zigbee knop schakelt thermostaat (universeel)
  description: Zet thermostaten aan of uit op basis van knopnummer en actie. Werkt met elk MQTT Zigbee-knopapparaat.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT topic van het apparaat
      description: Bijvoorbeeld `zigbee2mqtt/TS0043/action`
      selector:
        text:
    knopnummer:
      name: Knopnummer
      description: 1 = boven, 2 = midden, 3 = onder (afhankelijk van model)
      selector:
        number:
          min: 1
          max: 6
          step: 1
    actie_type:
      name: Actie type
      description: Typen die jouw knop ondersteunt, zoals `single`, `double`, `hold`, etc.
      selector:
        select:
          options:
            - single
            - double
            - hold
    thermostaten:
      name: Te schakelen thermostaten
      selector:
        entity:
          domain: climate
          multiple: true
    doelmodus:
      name: Nieuwe HVAC-modus
      selector:
        select:
          options:
            - "heat"
            - "off"

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

condition:
  - condition: template
    value_template: >
      {{ trigger.payload == (knopnummer | string) ~ '_' ~ actie_type }}

action:
  - repeat:
      for_each: !input thermostaten
      sequence:
        - service: climate.set_hvac_mode
          target:
            entity_id: "{{ repeat.item }}"
          data:
            hvac_mode: !input doelmodus

mode: single
